package upddwd.model.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 02 13:46:58 IST 2014
// ---------------------------------------------------------------------
public interface fileUpdDndAM extends ApplicationModule {
    void setFileData(String name, String path, String contTyp);
}

